name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 831532379331.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t clo835-app:latest .
        docker tag clo835-app:latest 831532379331.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest

    - name: Push to ECR
      run: |
        docker push 831532379331.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest
